// <auto-generated />
using System;
using EBYS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EBYS.Persistence.Migrations
{
    [DbContext(typeof(EBYSContext))]
    [Migration("20260518084117_UpdateGelenEvrakSevk")]
    partial class UpdateGelenEvrakSevk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EBYS.Domain.Entities.BaseKurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<string>("DetsisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KurumAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KurumKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("BaseKurums");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.EvrakKonuKodu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KodAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KodNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EvrakKonuKodlari");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GelenEvrak.GelenEvrak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CevapIstenenTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DefterTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DilekceMi")
                        .HasColumnType("boolean");

                    b.Property<string>("EvrakSayisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EvrakTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GizlilikDerecesi")
                        .HasColumnType("integer");

                    b.Property<int>("IvedilikDerecesi")
                        .HasColumnType("integer");

                    b.Property<string>("KayitNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KonuKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuhatapId")
                        .HasColumnType("integer");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("KayitNo")
                        .IsUnique();

                    b.HasIndex("MuhatapId");

                    b.HasIndex("OlusturanId");

                    b.ToTable("GelenEvraklar");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GelenEvrak.GelenEvrakEk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaUzantisi")
                        .HasColumnType("text");

                    b.Property<byte[]>("DosyaVerisi")
                        .HasColumnType("bytea");

                    b.Property<int?>("GelenEvrakId")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GelenEvrakId");

                    b.ToTable("GelenEvrakEkler");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GelenEvrak.GelenEvrakIlgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<int?>("GelenEvrakId")
                        .HasColumnType("integer");

                    b.Property<string>("IlgiMetni")
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GelenEvrakId");

                    b.ToTable("GelenEvrakIlgileri");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GelenEvrak.GelenEvrakSevk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("AlanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<int>("GelenEvrakId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OkunmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SevkEdenKullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SevkTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AlanKullaniciId");

                    b.HasIndex("GelenEvrakId");

                    b.HasIndex("SevkEdenKullaniciId");

                    b.ToTable("GelenEvrakSevkler");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<int>("BelgeDurum")
                        .HasColumnType("integer");

                    b.Property<int?>("EvrakSayisi")
                        .HasColumnType("integer");

                    b.Property<int>("GizlilikDerecesi")
                        .HasColumnType("integer");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImzaAltindaOlanIcerik")
                        .HasColumnType("text");

                    b.Property<int>("ImzaRotaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGelenEvrak")
                        .HasColumnType("boolean");

                    b.Property<int>("IvedilikDerecesi")
                        .HasColumnType("integer");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KonuKoduId")
                        .HasColumnType("integer");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ImzaRotaId");

                    b.HasIndex("KonuKoduId");

                    b.HasIndex("OlusturanId");

                    b.ToTable("Evraklar");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrakAkis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdimDurumu")
                        .HasColumnType("integer");

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<int>("EvrakId")
                        .HasColumnType("integer");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("Not")
                        .HasColumnType("text");

                    b.Property<int>("ParafMiImzaMi")
                        .HasColumnType("integer");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<bool>("SiradakiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EvrakId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("EvrakAkislari");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrakEk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaUzantisi")
                        .HasColumnType("text");

                    b.Property<byte[]>("DosyaVerisi")
                        .HasColumnType("bytea");

                    b.Property<int>("EvrakId")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EvrakId");

                    b.ToTable("EvrakEkler");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrakIlgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<int>("EvrakId")
                        .HasColumnType("integer");

                    b.Property<string>("IlgiMetni")
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EvrakId");

                    b.ToTable("EvrakIlgiler");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrakMuhatap", b =>
                {
                    b.Property<int>("EvrakId")
                        .HasColumnType("integer");

                    b.Property<int>("MuhatapId")
                        .HasColumnType("integer");

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBilgi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("EvrakId", "MuhatapId");

                    b.HasIndex("MuhatapId");

                    b.ToTable("EvrakMuhataplari");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.ImzaRota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<string>("RotaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ImzaRotalar");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.ImzaRotaAdimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<int>("ImzaRotaId")
                        .HasColumnType("integer");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("ParafMiImzaMi")
                        .HasColumnType("integer");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ImzaRotaId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("ImzaRotaAdimlari");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<string>("KimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BaseKurumId");

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Muhatap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<string>("EPosta")
                        .HasColumnType("text");

                    b.Property<string>("MuhatapTipi")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Muhataplar");

                    b.HasDiscriminator<string>("MuhatapTipi").HasValue("Muhatap");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseKurumId")
                        .HasColumnType("integer");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.BireyselMuhatap", b =>
                {
                    b.HasBaseType("EBYS.Domain.Entities.Muhatap");

                    b.Property<string>("KimlikNo")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Birey");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.KurumMuhatap", b =>
                {
                    b.HasBaseType("EBYS.Domain.Entities.Muhatap");

                    b.Property<string>("DetsisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KepAdresi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KurumKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TesisNo")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Kurum");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.TuzelKisiMuhatap", b =>
                {
                    b.HasBaseType("EBYS.Domain.Entities.Muhatap");

                    b.Property<string>("MersisNo")
                        .HasColumnType("text");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Tuzel");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GelenEvrak.GelenEvrak", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.Muhatap", "Muhatap")
                        .WithMany()
                        .HasForeignKey("MuhatapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBYS.Domain.Entities.Kullanici", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muhatap");

                    b.Navigation("Olusturan");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GelenEvrak.GelenEvrakEk", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.GelenEvrak.GelenEvrak", "GelenEvrak")
                        .WithMany("Ekler")
                        .HasForeignKey("GelenEvrakId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GelenEvrak");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GelenEvrak.GelenEvrakIlgi", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.GelenEvrak.GelenEvrak", "GelenEvrak")
                        .WithMany("Ilgileri")
                        .HasForeignKey("GelenEvrakId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GelenEvrak");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GelenEvrak.GelenEvrakSevk", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.Kullanici", "AlanKullanici")
                        .WithMany()
                        .HasForeignKey("AlanKullaniciId");

                    b.HasOne("EBYS.Domain.Entities.GelenEvrak.GelenEvrak", "GelenEvrak")
                        .WithMany("Sevkler")
                        .HasForeignKey("GelenEvrakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBYS.Domain.Entities.Kullanici", "SevkEdenKullanici")
                        .WithMany()
                        .HasForeignKey("SevkEdenKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlanKullanici");

                    b.Navigation("GelenEvrak");

                    b.Navigation("SevkEdenKullanici");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrak", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.ImzaRota", "ImzaRota")
                        .WithMany()
                        .HasForeignKey("ImzaRotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBYS.Domain.Entities.EvrakKonuKodu", "EvrakKonuKodu")
                        .WithMany()
                        .HasForeignKey("KonuKoduId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EBYS.Domain.Entities.Kullanici", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvrakKonuKodu");

                    b.Navigation("ImzaRota");

                    b.Navigation("Olusturan");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrakAkis", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.GidenEvrak.GidenEvrak", "Evrak")
                        .WithMany("AkisAdimlari")
                        .HasForeignKey("EvrakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBYS.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evrak");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrakEk", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.GidenEvrak.GidenEvrak", "Evrak")
                        .WithMany("Ekler")
                        .HasForeignKey("EvrakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evrak");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrakIlgi", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.GidenEvrak.GidenEvrak", "Evrak")
                        .WithMany("İlgiler")
                        .HasForeignKey("EvrakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evrak");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrakMuhatap", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.GidenEvrak.GidenEvrak", "Evrak")
                        .WithMany("Muhataplar")
                        .HasForeignKey("EvrakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBYS.Domain.Entities.Muhatap", "Muhatap")
                        .WithMany("Evraklar")
                        .HasForeignKey("MuhatapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evrak");

                    b.Navigation("Muhatap");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.ImzaRotaAdimi", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.ImzaRota", "Rota")
                        .WithMany("ImzaRotaAdimlari")
                        .HasForeignKey("ImzaRotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBYS.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Kullanici", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.BaseKurum", null)
                        .WithMany("Kullanicilar")
                        .HasForeignKey("BaseKurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBYS.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.BaseKurum", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GelenEvrak.GelenEvrak", b =>
                {
                    b.Navigation("Ekler");

                    b.Navigation("Ilgileri");

                    b.Navigation("Sevkler");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.GidenEvrak.GidenEvrak", b =>
                {
                    b.Navigation("AkisAdimlari");

                    b.Navigation("Ekler");

                    b.Navigation("Muhataplar");

                    b.Navigation("İlgiler");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.ImzaRota", b =>
                {
                    b.Navigation("ImzaRotaAdimlari");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Muhatap", b =>
                {
                    b.Navigation("Evraklar");
                });
#pragma warning restore 612, 618
        }
    }
}
