// <auto-generated />
using System;
using EBYS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EBYS.Persistence.Migrations
{
    [DbContext(typeof(EBYSContext))]
    partial class EBYSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EBYS.Domain.Entities.Evrak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BekleyenRolId")
                        .HasColumnType("integer");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("EvrakSayisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGelenEvrak")
                        .HasColumnType("boolean");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OlusturanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BekleyenRolId");

                    b.HasIndex("OlusturanId");

                    b.ToTable("Evraklar");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.EvrakEk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("text");

                    b.Property<string>("EkAdi")
                        .HasColumnType("text");

                    b.Property<int?>("EvrakId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EvrakId");

                    b.ToTable("EvrakEkler");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.EvrakIlgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EvrakId")
                        .HasColumnType("integer");

                    b.Property<string>("IlgiMetni")
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EvrakId");

                    b.ToTable("EvrakIlgiler");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.EvrakMuhatap", b =>
                {
                    b.Property<int>("EvrakId")
                        .HasColumnType("integer");

                    b.Property<int>("MuhatapId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBilgi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("EvrakId", "MuhatapId");

                    b.HasIndex("MuhatapId");

                    b.ToTable("EvrakMuhataplari");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Muhatap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EPosta")
                        .HasColumnType("text");

                    b.Property<string>("MuhatapTipi")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Muhataplar");

                    b.HasDiscriminator<string>("MuhatapTipi").HasValue("Muhatap");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("creat_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.BireyselMuhatap", b =>
                {
                    b.HasBaseType("EBYS.Domain.Entities.Muhatap");

                    b.Property<string>("KimlikNo")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Birey");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.KurumMuhatap", b =>
                {
                    b.HasBaseType("EBYS.Domain.Entities.Muhatap");

                    b.Property<string>("DetsisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KepAdresi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KurumKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TesisNo")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Kurum");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.TuzelKisiMuhatap", b =>
                {
                    b.HasBaseType("EBYS.Domain.Entities.Muhatap");

                    b.Property<string>("MersisNo")
                        .HasColumnType("text");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Tuzel");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Evrak", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.Rol", "BekleyenRol")
                        .WithMany()
                        .HasForeignKey("BekleyenRolId");

                    b.HasOne("EBYS.Domain.Entities.Kullanici", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BekleyenRol");

                    b.Navigation("Olusturan");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.EvrakEk", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.Evrak", null)
                        .WithMany("Ekler")
                        .HasForeignKey("EvrakId");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.EvrakIlgi", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.Evrak", null)
                        .WithMany("İlgiler")
                        .HasForeignKey("EvrakId");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.EvrakMuhatap", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.Evrak", "Evrak")
                        .WithMany("Muhataplar")
                        .HasForeignKey("EvrakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBYS.Domain.Entities.Muhatap", "Muhatap")
                        .WithMany("Evraklar")
                        .HasForeignKey("MuhatapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evrak");

                    b.Navigation("Muhatap");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Kullanici", b =>
                {
                    b.HasOne("EBYS.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Evrak", b =>
                {
                    b.Navigation("Ekler");

                    b.Navigation("Muhataplar");

                    b.Navigation("İlgiler");
                });

            modelBuilder.Entity("EBYS.Domain.Entities.Muhatap", b =>
                {
                    b.Navigation("Evraklar");
                });
#pragma warning restore 612, 618
        }
    }
}
